- hosts: webservers
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run web application container
      docker_container:
        name: web_app
        image: "{{ docker_hub_username }}/my-app:latest"
        state: started
        ports:
          - "80:5000"
